package com.garza.globalgraviton.network

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Notification
import android.content.Context
import android.content.Intent
import android.net.ConnectivityManager
import android.net.Network
import android.net.NetworkCapabilities
import android.net.NetworkRequest
import android.net.VpnService
import android.os.Build
import android.os.ParcelFileDescriptor
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.FileInputStream
import java.io.IOException
import java.net.DatagramSocket
import java.net.InetSocketAddress
import java.net.Socket
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

/**
 * Offline-first VPN/TUN prototype.
 *
 * The TUN descriptor exposes IP packets generated by local applications. A
 * production packet engine must parse those packets and forward them through a
 * real local proxy/tunnel protocol before writing valid response packets back
 * to the TUN descriptor. Network.bindSocket() binds those proxy sockets to a
 * selected physical Network; it does not itself forward arbitrary IP packets.
 */
class GravitonVpnService : VpnService() {
    private val serviceJob = SupervisorJob()
    private val ioScope = kotlinx.coroutines.CoroutineScope(serviceJob + Dispatchers.IO)
    private val running = AtomicBoolean(false)
    private val transports = ConcurrentHashMap<Network, Transport>()
    private lateinit var connectivityManager: ConnectivityManager
    private var tunInterface: ParcelFileDescriptor? = null

    private val networkCallback = object : ConnectivityManager.NetworkCallback() {
        override fun onCapabilitiesChanged(
            network: Network,
            capabilities: NetworkCapabilities
        ) {
            updateTransport(network, capabilities)
        }

        override fun onLost(network: Network) {
            transports.remove(network)?.close()
        }

        override fun onUnavailable() {
            selectTransport()
        }
    }

    override fun onCreate() {
        super.onCreate()
        connectivityManager =
            getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
        registerTransportCallbacks()
    }

    override fun onStartCommand(intent: android.content.Intent?, flags: Int, startId: Int): Int {
        startForeground(FOREGROUND_NOTIFICATION_ID, buildForegroundNotification())
        if (running.compareAndSet(false, true)) {
            establishTun()
            startPacketLoop()
        }
        return START_STICKY
    }

    private fun buildForegroundNotification(): Notification {
        val manager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                FOREGROUND_CHANNEL_ID,
                "Graviton VPN",
                NotificationManager.IMPORTANCE_LOW
            )
            manager.createNotificationChannel(channel)
        }
        return Notification.Builder(this, FOREGROUND_CHANNEL_ID)
            .setContentTitle("Global Graviton")
            .setContentText("Network optimizer tunnel active")
            .setSmallIcon(android.R.drawable.sym_def_app_icon)
            .setOngoing(true)
            .build()
    }

    private fun establishTun() {
        tunInterface = Builder()
            .setSession("Garza Global Graviton")
            .addAddress("10.77.0.2", 32)
            .addRoute("0.0.0.0", 0)
            .setBlocking(false)
            .establish()
            ?: error("Unable to establish the TUN interface")
    }

    private fun registerTransportCallbacks() {
        val request = NetworkRequest.Builder()
            .addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
            .addTransportType(NetworkCapabilities.TRANSPORT_WIFI)
            .addTransportType(NetworkCapabilities.TRANSPORT_CELLULAR)
            .build()
        connectivityManager.registerNetworkCallback(request, networkCallback)
    }

    private fun updateTransport(
        network: Network,
        capabilities: NetworkCapabilities
    ) {
        val kind = when {
            capabilities.hasTransport(NetworkCapabilities.TRANSPORT_WIFI) -> TransportKind.WIFI
            capabilities.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR) -> TransportKind.CELLULAR
            else -> return
        }
        transports.compute(network) { _, current ->
            val validated = capabilities.hasCapability(
                NetworkCapabilities.NET_CAPABILITY_VALIDATED
            )
            current?.copy(kind = kind, validated = validated)
                ?: Transport(network, kind, validated)
        }
    }

    /** Prefer validated Wi-Fi, then validated cellular, then any available link. */
    private fun selectTransport(): Transport? {
        return transports.values
            .sortedWith(
                compareByDescending<Transport> { it.validated }
                    .thenBy { it.kind.preference }
            )
            .firstOrNull()
    }

    /**
     * Open a proxy/tunnel socket on a selected physical network.
     * Call this for each flow or shard; never bind the process globally.
     */
    private fun openBoundSocket(
        transport: Transport,
        endpoint: InetSocketAddress
    ): Socket {
        val socket = Socket()
        try {
            protect(socket)
            transport.network.bindSocket(socket)
            socket.connect(endpoint, CONNECT_TIMEOUT_MS)
            return socket
        } catch (error: IOException) {
            socket.close()
            transports.remove(transport.network)
            throw error
        }
    }

    private fun openBoundDatagramSocket(transport: Transport): DatagramSocket {
        val socket = DatagramSocket(null)
        try {
            protect(socket)
            transport.network.bindSocket(socket)
            socket.bind(InetSocketAddress(0))
            return socket
        } catch (error: IOException) {
            socket.close()
            transports.remove(transport.network)
            throw error
        }
    }

    private fun startPacketLoop() {
        val tun = tunInterface ?: return
        ioScope.launch {
            FileInputStream(tun.fileDescriptor).use { input ->
                val packet = ByteArray(PACKET_BUFFER_SIZE)
                while (isActive && running.get()) {
                    try {
                        val length = withContext(Dispatchers.IO) {
                            input.read(packet)
                        }
                        if (length > 0) {
                            forwardPacketWithFailover(packet, length)
                        }
                    } catch (error: IOException) {
                        if (running.get()) {
                            recoverFromTransportFailure(error)
                        }
                    } catch (_: CancellationException) {
                        ensureActive()
                    }
                }
            }
        }
    }

    /**
     * Minimal flow-level failover policy. A real implementation should retain
     * flow state and replay only protocol-safe data through the next transport.
     */
    private suspend fun forwardPacketWithFailover(packet: ByteArray, length: Int) {
        val candidates = transports.values
            .sortedWith(compareByDescending<Transport> { it.validated }
                .thenBy { it.kind.preference })
        for (candidate in candidates) {
            try {
                forwardThroughProxy(candidate, packet, length)
                return
            } catch (error: IOException) {
                transports.remove(candidate.network)
                candidate.close()
            }
        }
        recoverFromTransportFailure(IOException("No usable network transport"))
    }

    private suspend fun forwardThroughProxy(
        transport: Transport,
        packet: ByteArray,
        length: Int
    ) = withContext(Dispatchers.IO) {
        // Replace with the local authenticated proxy/tunnel framing protocol.
        // Raw packet bytes must not be sent directly to an arbitrary endpoint.
        val endpoint = InetSocketAddress(
            GravitonGatewayConfig.HOST,
            GravitonGatewayConfig.PORT
        )
        openBoundSocket(transport, endpoint).use { proxy ->
            proxy.getOutputStream().write(packet, 0, length)
            proxy.getOutputStream().flush()
        }
    }

    private suspend fun recoverFromTransportFailure(error: IOException) {
        selectTransport()
        // Backoff belongs here in the production policy; keep the loop alive
        // while callbacks repopulate the transport map.
        kotlinx.coroutines.yield()
    }

    override fun onRevoke() {
        stopService()
        super.onRevoke()
    }

    override fun onDestroy() {
        stopService()
        connectivityManager.unregisterNetworkCallback(networkCallback)
        serviceJob.cancel()
        super.onDestroy()
    }

    private fun stopService() {
        if (running.compareAndSet(true, false)) {
            tunInterface?.close()
            tunInterface = null
            transports.values.forEach(Transport::close)
            transports.clear()
        }
    }

    private data class Transport(
        val network: Network,
        val kind: TransportKind,
        val validated: Boolean
    ) {
        fun close() = Unit
    }

    private enum class TransportKind(val preference: Int) {
        WIFI(0),
        CELLULAR(1)
    }

    private companion object {
        const val PACKET_BUFFER_SIZE = 32 * 1024
        const val CONNECT_TIMEOUT_MS = 5_000
        const val FOREGROUND_CHANNEL_ID = "ggg_vpn_channel"
        const val FOREGROUND_NOTIFICATION_ID = 1
    }
}
